<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.1.0</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<ApplicationIcon>Resources\AppIcon\icon3.ico</ApplicationIcon>
	  <!--<PublishAot>true</PublishAot>
    <TrimMode>link</TrimMode>-->
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\AppIcon\icon.ico" />
    <None Remove="Resources\AppIcon\icon2.ico" />
    <None Remove="Resources\AppIcon\icon3.ico" />
    <None Remove="Resources\SoundPack\alarm-bell.mp3" />
    <None Remove="Resources\SoundPack\be-be-be-be-be-be-be-be-be-.mp3" />
    <None Remove="Resources\SoundPack\be-be-be-beep.mp3" />
    <None Remove="Resources\SoundPack\be-be-be-beep2.mp3" />
    <None Remove="Resources\SoundPack\be-beep.mp3" />
    <None Remove="Resources\SoundPack\beep-beep-beep.mp3" />
    <None Remove="Resources\SoundPack\beep-beep.mp3" />
    <None Remove="Resources\SoundPack\bio-harzard-alert.mp3" />
    <None Remove="Resources\SoundPack\harzard-alert.mp3" />
    <None Remove="Resources\SoundPack\mixed.mp3" />
    <None Remove="Resources\SoundPack\music-box.mp3" />
    <None Remove="Resources\SoundPack\old-phone-alarm.mp3" />
    <None Remove="Resources\SoundPack\school-bell.mp3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdsJumbo.WinForm.WPF" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon\icon.ico" />
    <Resource Include="Resources\AppIcon\icon2.ico" />
    <Resource Include="Resources\AppIcon\icon3.ico" />
    <Resource Include="Resources\SoundPack\alarm-bell.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\be-be-be-be-be-be-be-be-be-.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\be-be-be-beep.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\be-be-be-beep2.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\be-beep.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\beep-beep-beep.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\beep-beep.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\bio-harzard-alert.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\harzard-alert.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\mixed.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\music-box.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\old-phone-alarm.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\SoundPack\school-bell.mp3">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
